In [1]:
import numpy as np

In [24]:
array1 = np.array([0,2])
array2 = np.array([2,0]).reshape(-1,1)
array3 = np.array([0,2]).reshape(-1,1)

In [25]:
array3

array([[0],
       [2]])

In [26]:
array2

array([[2],
       [0]])

In [15]:
array1

array([0, 2])

In [6]:
np.matmul(array1, array2)

array([0])

In [27]:
np.dot(array2,array3)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

In [12]:
array1 @ array2

array([0])